# Generated by Django 2.0.7 on 2019-04-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20190404_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ceo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='founded_on',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='founders',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='headquarters',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
