# Generated by Django 2.0.7 on 2019-04-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20190404_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='ceo',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='founded_on',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='founders',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='headquarters',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='url',
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_data',
            field=models.TextField(default='Temp'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
