# Generated by Django 2.0.7 on 2019-04-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_auto_20190412_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='price',
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_name',
            field=models.CharField(max_length=20),
        ),
    ]
