# Generated by Django 2.0.7 on 2019-04-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_auto_20190412_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='is_Downloaded',
            new_name='is_downloaded',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='stock_data',
            new_name='table_data',
        ),
    ]
